import { PrismaClient, VehicleType } from '@prisma/client';

const prisma = new PrismaClient();

// ======================================================
// Türkiye Otoyol & Köprü Gişe Ücretleri
// Kaynak: KGM Resmi PDF'leri — 01.01.2026 Tarifeleri
// https://www.kgm.gov.tr/Sayfalar/KGM/SiteTr/Otoyollar/UcretlerYeni.aspx
// ======================================================
// Sınıflar:
//   1. Sınıf = Otomobil (CAR)
//   2. Sınıf = Minibüs/Van (VAN)
//   3. Sınıf = Otobüs (BUS)
//   4. Sınıf = Kamyon (TRUCK)
//   6. Sınıf = Motosiklet (MOTORCYCLE)

interface TollStationData {
    name: string;
    location: string;
    highway: string;
    lat: number;
    lng: number;
    rates: { vehicleType: VehicleType; amount: number }[];
}

const tollStations: TollStationData[] = [
    // ==========================================
    // KÖPRÜLER (Bridge Tolls)
    // ==========================================
    {
        name: '15 Temmuz Şehitler Köprüsü',
        location: 'İstanbul Boğaziçi',
        highway: 'Köprü',
        lat: 41.0451,
        lng: 29.0344,
        rates: [
            { vehicleType: 'CAR', amount: 59 },
            { vehicleType: 'MOTORCYCLE', amount: 25 },
            { vehicleType: 'VAN', amount: 75 },
            { vehicleType: 'BUS', amount: 168 },
            { vehicleType: 'TRUCK', amount: 333 },
        ],
    },
    {
        name: 'Fatih Sultan Mehmet Köprüsü',
        location: 'İstanbul Boğaziçi',
        highway: 'Köprü',
        lat: 41.0893,
        lng: 29.0638,
        rates: [
            { vehicleType: 'CAR', amount: 59 },
            { vehicleType: 'MOTORCYCLE', amount: 25 },
            { vehicleType: 'VAN', amount: 75 },
            { vehicleType: 'BUS', amount: 168 },
            { vehicleType: 'TRUCK', amount: 333 },
        ],
    },
    {
        name: 'Yavuz Sultan Selim Köprüsü',
        location: 'İstanbul 3. Köprü',
        highway: 'Köprü',
        lat: 41.2080,
        lng: 29.1172,
        rates: [
            { vehicleType: 'CAR', amount: 95 },
            { vehicleType: 'MOTORCYCLE', amount: 65 },
            { vehicleType: 'VAN', amount: 125 },
            { vehicleType: 'BUS', amount: 235 },
            { vehicleType: 'TRUCK', amount: 595 },
        ],
    },
    {
        name: 'Osmangazi Köprüsü',
        location: 'Kocaeli-Bursa İzmit Körfezi',
        highway: 'Köprü',
        lat: 40.7169,
        lng: 29.5094,
        rates: [
            { vehicleType: 'CAR', amount: 995 },
            { vehicleType: 'MOTORCYCLE', amount: 695 },
            { vehicleType: 'VAN', amount: 1590 },
            { vehicleType: 'BUS', amount: 1890 },
            { vehicleType: 'TRUCK', amount: 2505 },
        ],
    },
    {
        name: '1915 Çanakkale Köprüsü',
        location: 'Çanakkale Lapseki-Gelibolu',
        highway: 'Köprü',
        lat: 40.3372,
        lng: 26.6650,
        rates: [
            { vehicleType: 'CAR', amount: 995 },
            { vehicleType: 'MOTORCYCLE', amount: 250 },
            { vehicleType: 'VAN', amount: 1245 },
            { vehicleType: 'BUS', amount: 2240 },
            { vehicleType: 'TRUCK', amount: 2490 },
        ],
    },
    {
        name: 'Avrasya Tüneli',
        location: 'İstanbul Kazlıçeşme-Göztepe',
        highway: 'Tünel',
        lat: 41.0042,
        lng: 28.9780,
        rates: [
            { vehicleType: 'CAR', amount: 250 },
            { vehicleType: 'MOTORCYCLE', amount: 175 },
            { vehicleType: 'VAN', amount: 375 },
            { vehicleType: 'BUS', amount: 0 },
            { vehicleType: 'TRUCK', amount: 0 },
        ],
    },

    // ==========================================
    // ANADOLU OTOYOLU (O-4) — Çamlıca → Akıncı (İstanbul-Ankara)
    // KGM 2026: Tam rota 1.Sınıf = 338₺
    // Gişeler arası kümülatif ücretler
    // ==========================================
    {
        name: 'Samandıra Gişeleri',
        location: 'İstanbul Samandıra',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.9650,
        lng: 29.2180,
        rates: [
            { vehicleType: 'CAR', amount: 40 },
            { vehicleType: 'MOTORCYCLE', amount: 16 },
            { vehicleType: 'VAN', amount: 48 },
            { vehicleType: 'BUS', amount: 57 },
            { vehicleType: 'TRUCK', amount: 75 },
        ],
    },
    {
        name: 'Kurtköy Gişeleri',
        location: 'İstanbul Kurtköy',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.9103,
        lng: 29.3070,
        rates: [
            { vehicleType: 'CAR', amount: 49 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 59 },
            { vehicleType: 'BUS', amount: 70 },
            { vehicleType: 'TRUCK', amount: 93 },
        ],
    },
    {
        name: 'Gebze Gişeleri (O-4)',
        location: 'Kocaeli Gebze',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.7986,
        lng: 29.4311,
        rates: [
            { vehicleType: 'CAR', amount: 49 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 59 },
            { vehicleType: 'BUS', amount: 70 },
            { vehicleType: 'TRUCK', amount: 93 },
        ],
    },
    {
        name: 'Diliskelesi Gişeleri',
        location: 'Kocaeli Diliskelesi',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.7635,
        lng: 29.5350,
        rates: [
            { vehicleType: 'CAR', amount: 56 },
            { vehicleType: 'MOTORCYCLE', amount: 23 },
            { vehicleType: 'VAN', amount: 67 },
            { vehicleType: 'BUS', amount: 80 },
            { vehicleType: 'TRUCK', amount: 106 },
        ],
    },
    {
        name: 'Körfez Gişeleri (O-4)',
        location: 'Kocaeli Körfez',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.7365,
        lng: 29.7426,
        rates: [
            { vehicleType: 'CAR', amount: 71 },
            { vehicleType: 'MOTORCYCLE', amount: 29 },
            { vehicleType: 'VAN', amount: 85 },
            { vehicleType: 'BUS', amount: 101 },
            { vehicleType: 'TRUCK', amount: 134 },
        ],
    },
    {
        name: 'Doğu İzmit Gişeleri',
        location: 'Kocaeli İzmit',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.7660,
        lng: 29.9540,
        rates: [
            { vehicleType: 'CAR', amount: 82 },
            { vehicleType: 'MOTORCYCLE', amount: 33 },
            { vehicleType: 'VAN', amount: 98 },
            { vehicleType: 'BUS', amount: 117 },
            { vehicleType: 'TRUCK', amount: 155 },
        ],
    },
    {
        name: 'Sapanca Gişeleri',
        location: 'Sakarya Sapanca',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.6919,
        lng: 30.2729,
        rates: [
            { vehicleType: 'CAR', amount: 102 },
            { vehicleType: 'MOTORCYCLE', amount: 41 },
            { vehicleType: 'VAN', amount: 122 },
            { vehicleType: 'BUS', amount: 146 },
            { vehicleType: 'TRUCK', amount: 193 },
        ],
    },
    {
        name: 'Adapazarı Gişeleri',
        location: 'Sakarya Adapazarı',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.6768,
        lng: 30.4028,
        rates: [
            { vehicleType: 'CAR', amount: 115 },
            { vehicleType: 'MOTORCYCLE', amount: 46 },
            { vehicleType: 'VAN', amount: 138 },
            { vehicleType: 'BUS', amount: 164 },
            { vehicleType: 'TRUCK', amount: 218 },
        ],
    },
    {
        name: 'Akyazı Gişeleri (O-4)',
        location: 'Sakarya Akyazı',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.6875,
        lng: 30.6206,
        rates: [
            { vehicleType: 'CAR', amount: 136 },
            { vehicleType: 'MOTORCYCLE', amount: 55 },
            { vehicleType: 'VAN', amount: 163 },
            { vehicleType: 'BUS', amount: 195 },
            { vehicleType: 'TRUCK', amount: 258 },
        ],
    },
    {
        name: 'Hendek Gişeleri',
        location: 'Sakarya Hendek',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.7925,
        lng: 30.7500,
        rates: [
            { vehicleType: 'CAR', amount: 158 },
            { vehicleType: 'MOTORCYCLE', amount: 64 },
            { vehicleType: 'VAN', amount: 190 },
            { vehicleType: 'BUS', amount: 226 },
            { vehicleType: 'TRUCK', amount: 300 },
        ],
    },
    {
        name: 'Düzce (Gölyaka) Gişeleri',
        location: 'Düzce Gölyaka',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.7890,
        lng: 31.0310,
        rates: [
            { vehicleType: 'CAR', amount: 222 },
            { vehicleType: 'MOTORCYCLE', amount: 89 },
            { vehicleType: 'VAN', amount: 264 },
            { vehicleType: 'BUS', amount: 315 },
            { vehicleType: 'TRUCK', amount: 417 },
        ],
    },
    {
        name: 'Kaynaşlı Gişeleri',
        location: 'Düzce Kaynaşlı',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.7700,
        lng: 31.3200,
        rates: [
            { vehicleType: 'CAR', amount: 233 },
            { vehicleType: 'MOTORCYCLE', amount: 94 },
            { vehicleType: 'VAN', amount: 278 },
            { vehicleType: 'BUS', amount: 332 },
            { vehicleType: 'TRUCK', amount: 440 },
        ],
    },
    {
        name: 'Bolu Batı Gişeleri',
        location: 'Bolu',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.7310,
        lng: 31.5841,
        rates: [
            { vehicleType: 'CAR', amount: 289 },
            { vehicleType: 'MOTORCYCLE', amount: 116 },
            { vehicleType: 'VAN', amount: 340 },
            { vehicleType: 'BUS', amount: 406 },
            { vehicleType: 'TRUCK', amount: 538 },
        ],
    },
    {
        name: 'Gerede Gişeleri',
        location: 'Bolu Gerede',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 40.7990,
        lng: 32.2010,
        rates: [
            { vehicleType: 'CAR', amount: 338 },
            { vehicleType: 'MOTORCYCLE', amount: 136 },
            { vehicleType: 'VAN', amount: 390 },
            { vehicleType: 'BUS', amount: 522 },
            { vehicleType: 'TRUCK', amount: 675 },
        ],
    },
    {
        name: 'Akıncı Gişeleri (Ankara)',
        location: 'Ankara',
        highway: 'Anadolu Otoyolu (O-4)',
        lat: 39.9826,
        lng: 32.7370,
        rates: [
            { vehicleType: 'CAR', amount: 338 },
            { vehicleType: 'MOTORCYCLE', amount: 136 },
            { vehicleType: 'VAN', amount: 390 },
            { vehicleType: 'BUS', amount: 522 },
            { vehicleType: 'TRUCK', amount: 675 },
        ],
    },

    // ==========================================
    // AVRUPA OTOYOLU (O-3) — Mahmutbey → Edirne
    // KGM 2026: Tam rota 1.Sınıf = 168₺ (FIXED from 378₺ error)
    // ==========================================
    {
        name: 'Mahmutbey Gişeleri',
        location: 'İstanbul Mahmutbey',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.0647,
        lng: 28.8008,
        rates: [
            { vehicleType: 'CAR', amount: 168 },
            { vehicleType: 'MOTORCYCLE', amount: 69 },
            { vehicleType: 'VAN', amount: 193 },
            { vehicleType: 'BUS', amount: 256 },
            { vehicleType: 'TRUCK', amount: 338 },
        ],
    },
    {
        name: 'Ispartakule Gişeleri',
        location: 'İstanbul Ispartakule',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.0450,
        lng: 28.8650,
        rates: [
            { vehicleType: 'CAR', amount: 49 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 58 },
            { vehicleType: 'BUS', amount: 77 },
            { vehicleType: 'TRUCK', amount: 101 },
        ],
    },
    {
        name: 'Avcılar Gişeleri',
        location: 'İstanbul Avcılar',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.0350,
        lng: 28.7350,
        rates: [
            { vehicleType: 'CAR', amount: 49 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 58 },
            { vehicleType: 'BUS', amount: 77 },
            { vehicleType: 'TRUCK', amount: 101 },
        ],
    },
    {
        name: 'Esenyurt Gişeleri',
        location: 'İstanbul Esenyurt',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.0180,
        lng: 28.7100,
        rates: [
            { vehicleType: 'CAR', amount: 49 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 58 },
            { vehicleType: 'BUS', amount: 77 },
            { vehicleType: 'TRUCK', amount: 101 },
        ],
    },
    {
        name: 'Hadımköy Gişeleri',
        location: 'İstanbul Hadımköy',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.0980,
        lng: 28.6520,
        rates: [
            { vehicleType: 'CAR', amount: 49 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 58 },
            { vehicleType: 'BUS', amount: 77 },
            { vehicleType: 'TRUCK', amount: 101 },
        ],
    },
    {
        name: 'Çatalca Gişeleri',
        location: 'İstanbul Çatalca',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.1380,
        lng: 28.4630,
        rates: [
            { vehicleType: 'CAR', amount: 49 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 58 },
            { vehicleType: 'BUS', amount: 77 },
            { vehicleType: 'TRUCK', amount: 101 },
        ],
    },
    {
        name: 'Kınalı Gişeleri',
        location: 'İstanbul Kınalı',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.1780,
        lng: 28.2980,
        rates: [
            { vehicleType: 'CAR', amount: 73 },
            { vehicleType: 'MOTORCYCLE', amount: 30 },
            { vehicleType: 'VAN', amount: 85 },
            { vehicleType: 'BUS', amount: 113 },
            { vehicleType: 'TRUCK', amount: 149 },
        ],
    },
    {
        name: 'Selimpaşa Gişeleri',
        location: 'Tekirdağ Selimpaşa',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 40.9850,
        lng: 27.5920,
        rates: [
            { vehicleType: 'CAR', amount: 73 },
            { vehicleType: 'MOTORCYCLE', amount: 30 },
            { vehicleType: 'VAN', amount: 85 },
            { vehicleType: 'BUS', amount: 113 },
            { vehicleType: 'TRUCK', amount: 149 },
        ],
    },
    {
        name: 'Silivri Gişeleri',
        location: 'İstanbul Silivri',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.0670,
        lng: 28.7320,
        rates: [
            { vehicleType: 'CAR', amount: 73 },
            { vehicleType: 'MOTORCYCLE', amount: 30 },
            { vehicleType: 'VAN', amount: 85 },
            { vehicleType: 'BUS', amount: 113 },
            { vehicleType: 'TRUCK', amount: 149 },
        ],
    },
    {
        name: 'Kınalı Gişeleri (O-3)',
        location: 'İstanbul Kınalı',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.1850,
        lng: 28.3020,
        rates: [
            { vehicleType: 'CAR', amount: 73 },
            { vehicleType: 'MOTORCYCLE', amount: 30 },
            { vehicleType: 'VAN', amount: 85 },
            { vehicleType: 'BUS', amount: 113 },
            { vehicleType: 'TRUCK', amount: 149 },
        ],
    },
    {
        name: 'Çerkezköy Gişeleri',
        location: 'Tekirdağ Çerkezköy',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.2880,
        lng: 27.8850,
        rates: [
            { vehicleType: 'CAR', amount: 73 },
            { vehicleType: 'MOTORCYCLE', amount: 30 },
            { vehicleType: 'VAN', amount: 85 },
            { vehicleType: 'BUS', amount: 113 },
            { vehicleType: 'TRUCK', amount: 149 },
        ],
    },
    {
        name: 'Çorlu Gişeleri',
        location: 'Tekirdağ Çorlu',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.2100,
        lng: 27.8020,
        rates: [
            { vehicleType: 'CAR', amount: 73 },
            { vehicleType: 'MOTORCYCLE', amount: 30 },
            { vehicleType: 'VAN', amount: 85 },
            { vehicleType: 'BUS', amount: 113 },
            { vehicleType: 'TRUCK', amount: 149 },
        ],
    },
    {
        name: 'Saray Gişeleri',
        location: 'Tekirdağ Saray',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.3620,
        lng: 27.4150,
        rates: [
            { vehicleType: 'CAR', amount: 73 },
            { vehicleType: 'MOTORCYCLE', amount: 30 },
            { vehicleType: 'VAN', amount: 85 },
            { vehicleType: 'BUS', amount: 113 },
            { vehicleType: 'TRUCK', amount: 149 },
        ],
    },
    {
        name: 'Lüleburgaz Gişeleri',
        location: 'Kırklareli Lüleburgaz',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.3990,
        lng: 27.3620,
        rates: [
            { vehicleType: 'CAR', amount: 134 },
            { vehicleType: 'MOTORCYCLE', amount: 54 },
            { vehicleType: 'VAN', amount: 155 },
            { vehicleType: 'BUS', amount: 206 },
            { vehicleType: 'TRUCK', amount: 272 },
        ],
    },
    {
        name: 'Babaeski Gişeleri',
        location: 'Kırklareli Babaeski',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.4750,
        lng: 27.4580,
        rates: [
            { vehicleType: 'CAR', amount: 134 },
            { vehicleType: 'MOTORCYCLE', amount: 54 },
            { vehicleType: 'VAN', amount: 155 },
            { vehicleType: 'BUS', amount: 206 },
            { vehicleType: 'TRUCK', amount: 272 },
        ],
    },
    {
        name: 'Havsa Gişeleri',
        location: 'Edirne Havsa',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.5820,
        lng: 26.4940,
        rates: [
            { vehicleType: 'CAR', amount: 168 },
            { vehicleType: 'MOTORCYCLE', amount: 69 },
            { vehicleType: 'VAN', amount: 193 },
            { vehicleType: 'BUS', amount: 256 },
            { vehicleType: 'TRUCK', amount: 338 },
        ],
    },
    {
        name: 'Edirne Gişeleri',
        location: 'Edirne',
        highway: 'Avrupa Otoyolu (O-3)',
        lat: 41.6725,
        lng: 26.5557,
        rates: [
            { vehicleType: 'CAR', amount: 168 },
            { vehicleType: 'MOTORCYCLE', amount: 69 },
            { vehicleType: 'VAN', amount: 193 },
            { vehicleType: 'BUS', amount: 256 },
            { vehicleType: 'TRUCK', amount: 338 },
        ],
    },

    // ==========================================
    // İSTANBUL-İZMİR OTOYOLU (O-5) — Orhangazi → İzmir
    // KGM 2026: Osmangazi Köprüsü + Otoyol
    // Osmangazi Köprüsü zaten Köprü bölümünde (995₺)
    // Bu gişeler köprüden sonra otoyol kısmı
    // ==========================================
    {
        name: 'Orhangazi Gişeleri',
        location: 'Bursa Orhangazi',
        highway: 'İstanbul-İzmir Otoyolu (O-5)',
        lat: 40.4890,
        lng: 29.3170,
        rates: [
            { vehicleType: 'CAR', amount: 50 },
            { vehicleType: 'MOTORCYCLE', amount: 35 },
            { vehicleType: 'VAN', amount: 80 },
            { vehicleType: 'BUS', amount: 95 },
            { vehicleType: 'TRUCK', amount: 125 },
        ],
    },
    {
        name: 'Bursa Kuzey Gişeleri',
        location: 'Bursa Kuzey',
        highway: 'İstanbul-İzmir Otoyolu (O-5)',
        lat: 40.2650,
        lng: 29.0780,
        rates: [
            { vehicleType: 'CAR', amount: 50 },
            { vehicleType: 'MOTORCYCLE', amount: 60 },
            { vehicleType: 'VAN', amount: 105 },
            { vehicleType: 'BUS', amount: 125 },
            { vehicleType: 'TRUCK', amount: 165 },
        ],
    },
    {
        name: 'Karacabey Gişeleri',
        location: 'Bursa Karacabey',
        highway: 'İstanbul-İzmir Otoyolu (O-5)',
        lat: 40.2191,
        lng: 28.3600,
        rates: [
            { vehicleType: 'CAR', amount: 215 },
            { vehicleType: 'MOTORCYCLE', amount: 150 },
            { vehicleType: 'VAN', amount: 345 },
            { vehicleType: 'BUS', amount: 405 },
            { vehicleType: 'TRUCK', amount: 540 },
        ],
    },
    {
        name: 'Balıkesir Batı Gişeleri',
        location: 'Balıkesir',
        highway: 'İstanbul-İzmir Otoyolu (O-5)',
        lat: 39.6500,
        lng: 27.8820,
        rates: [
            { vehicleType: 'CAR', amount: 420 },
            { vehicleType: 'MOTORCYCLE', amount: 295 },
            { vehicleType: 'VAN', amount: 675 },
            { vehicleType: 'BUS', amount: 800 },
            { vehicleType: 'TRUCK', amount: 1055 },
        ],
    },
    {
        name: 'Akhisar Gişeleri',
        location: 'Manisa Akhisar',
        highway: 'İstanbul-İzmir Otoyolu (O-5)',
        lat: 38.9170,
        lng: 27.8380,
        rates: [
            { vehicleType: 'CAR', amount: 600 },
            { vehicleType: 'MOTORCYCLE', amount: 420 },
            { vehicleType: 'VAN', amount: 960 },
            { vehicleType: 'BUS', amount: 1140 },
            { vehicleType: 'TRUCK', amount: 1505 },
        ],
    },
    {
        name: 'Turgutlu Gişeleri',
        location: 'Manisa Turgutlu',
        highway: 'İstanbul-İzmir Otoyolu (O-5)',
        lat: 38.5000,
        lng: 27.7050,
        rates: [
            { vehicleType: 'CAR', amount: 870 },
            { vehicleType: 'MOTORCYCLE', amount: 610 },
            { vehicleType: 'VAN', amount: 1395 },
            { vehicleType: 'BUS', amount: 1655 },
            { vehicleType: 'TRUCK', amount: 2185 },
        ],
    },
    {
        name: 'İzmir Çıkış Gişeleri',
        location: 'İzmir',
        highway: 'İstanbul-İzmir Otoyolu (O-5)',
        lat: 38.4580,
        lng: 27.2150,
        rates: [
            { vehicleType: 'CAR', amount: 970 },
            { vehicleType: 'MOTORCYCLE', amount: 680 },
            { vehicleType: 'VAN', amount: 1555 },
            { vehicleType: 'BUS', amount: 1845 },
            { vehicleType: 'TRUCK', amount: 2440 },
        ],
    },

    // ==========================================
    // İZMİR-ÇEŞME OTOYOLU (O-32) — Seferihisar → Çeşme
    // KGM 2026 PDF 6: Tam rota 1.Sınıf = 53₺
    // ==========================================
    {
        name: 'Seferihisar (Güzelbahçe) Gişeleri',
        location: 'İzmir Seferihisar',
        highway: 'İzmir-Çeşme Otoyolu (O-32)',
        lat: 38.3640,
        lng: 26.8690,
        rates: [
            { vehicleType: 'CAR', amount: 53 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 56 },
            { vehicleType: 'BUS', amount: 102 },
            { vehicleType: 'TRUCK', amount: 115 },
        ],
    },
    {
        name: 'Urla Gişeleri',
        location: 'İzmir Urla',
        highway: 'İzmir-Çeşme Otoyolu (O-32)',
        lat: 38.3210,
        lng: 26.7630,
        rates: [
            { vehicleType: 'CAR', amount: 49 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 53 },
            { vehicleType: 'BUS', amount: 56 },
            { vehicleType: 'TRUCK', amount: 69 },
        ],
    },
    {
        name: 'Karaburun Gişeleri',
        location: 'İzmir Karaburun',
        highway: 'İzmir-Çeşme Otoyolu (O-32)',
        lat: 38.3050,
        lng: 26.6900,
        rates: [
            { vehicleType: 'CAR', amount: 49 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 56 },
            { vehicleType: 'BUS', amount: 59 },
            { vehicleType: 'TRUCK', amount: 73 },
        ],
    },
    {
        name: 'Zeytinler Gişeleri',
        location: 'İzmir Zeytinler',
        highway: 'İzmir-Çeşme Otoyolu (O-32)',
        lat: 38.2850,
        lng: 26.5850,
        rates: [
            { vehicleType: 'CAR', amount: 53 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 56 },
            { vehicleType: 'BUS', amount: 65 },
            { vehicleType: 'TRUCK', amount: 102 },
        ],
    },
    {
        name: 'Alaçatı Gişeleri',
        location: 'İzmir Alaçatı',
        highway: 'İzmir-Çeşme Otoyolu (O-32)',
        lat: 38.2800,
        lng: 26.4990,
        rates: [
            { vehicleType: 'CAR', amount: 53 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 56 },
            { vehicleType: 'BUS', amount: 102 },
            { vehicleType: 'TRUCK', amount: 115 },
        ],
    },
    {
        name: 'Çeşme Gişeleri',
        location: 'İzmir Çeşme',
        highway: 'İzmir-Çeşme Otoyolu (O-32)',
        lat: 38.3230,
        lng: 26.3920,
        rates: [
            { vehicleType: 'CAR', amount: 53 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 56 },
            { vehicleType: 'BUS', amount: 102 },
            { vehicleType: 'TRUCK', amount: 115 },
        ],
    },

    // ==========================================
    // İZMİR-AYDIN OTOYOLU — Işıkkent → Aydın Batı
    // KGM 2026 PDF 7: Tam rota 1.Sınıf = 73₺
    // ==========================================
    {
        name: 'Işıkkent Gişeleri',
        location: 'İzmir Işıkkent',
        highway: 'İzmir-Aydın Otoyolu',
        lat: 38.3870,
        lng: 27.1450,
        rates: [
            { vehicleType: 'CAR', amount: 73 },
            { vehicleType: 'MOTORCYCLE', amount: 33 },
            { vehicleType: 'VAN', amount: 82 },
            { vehicleType: 'BUS', amount: 115 },
            { vehicleType: 'TRUCK', amount: 148 },
        ],
    },
    {
        name: 'Tahtaliçay (Havalimanı) Gişeleri',
        location: 'İzmir Tahtaliçay',
        highway: 'İzmir-Aydın Otoyolu',
        lat: 38.3100,
        lng: 27.1550,
        rates: [
            { vehicleType: 'CAR', amount: 40 },
            { vehicleType: 'MOTORCYCLE', amount: 15 },
            { vehicleType: 'VAN', amount: 45 },
            { vehicleType: 'BUS', amount: 56 },
            { vehicleType: 'TRUCK', amount: 69 },
        ],
    },
    {
        name: 'Torbalı Gişeleri',
        location: 'İzmir Torbalı',
        highway: 'İzmir-Aydın Otoyolu',
        lat: 38.1680,
        lng: 27.3670,
        rates: [
            { vehicleType: 'CAR', amount: 49 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 56 },
            { vehicleType: 'BUS', amount: 65 },
            { vehicleType: 'TRUCK', amount: 102 },
        ],
    },
    {
        name: 'Belevi Gişeleri',
        location: 'Aydın Belevi',
        highway: 'İzmir-Aydın Otoyolu',
        lat: 37.9850,
        lng: 27.5270,
        rates: [
            { vehicleType: 'CAR', amount: 53 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 56 },
            { vehicleType: 'BUS', amount: 65 },
            { vehicleType: 'TRUCK', amount: 115 },
        ],
    },
    {
        name: 'Germencik Gişeleri',
        location: 'Aydın Germencik',
        highway: 'İzmir-Aydın Otoyolu',
        lat: 37.8690,
        lng: 27.6060,
        rates: [
            { vehicleType: 'CAR', amount: 73 },
            { vehicleType: 'MOTORCYCLE', amount: 33 },
            { vehicleType: 'VAN', amount: 82 },
            { vehicleType: 'BUS', amount: 102 },
            { vehicleType: 'TRUCK', amount: 115 },
        ],
    },
    {
        name: 'Aydın Batı Gişeleri',
        location: 'Aydın Batı',
        highway: 'İzmir-Aydın Otoyolu',
        lat: 37.8530,
        lng: 27.8050,
        rates: [
            { vehicleType: 'CAR', amount: 73 },
            { vehicleType: 'MOTORCYCLE', amount: 33 },
            { vehicleType: 'VAN', amount: 82 },
            { vehicleType: 'BUS', amount: 115 },
            { vehicleType: 'TRUCK', amount: 148 },
        ],
    },

    // ==========================================
    // ÇUKUROVA OTOYOLU — Adana-Gaziantep
    // KGM 2026 PDF 8: Tam rota 1.Sınıf = 102₺
    // ==========================================
    {
        name: 'Adana Doğu Alın Gişeleri',
        location: 'Adana Doğu',
        highway: 'Çukurova Otoyolu (Adana-Gaziantep)',
        lat: 37.0220,
        lng: 35.4100,
        rates: [
            { vehicleType: 'CAR', amount: 102 },
            { vehicleType: 'MOTORCYCLE', amount: 45 },
            { vehicleType: 'VAN', amount: 120 },
            { vehicleType: 'BUS', amount: 156 },
            { vehicleType: 'TRUCK', amount: 205 },
        ],
    },
    {
        name: 'Ceyhan Gişeleri',
        location: 'Adana Ceyhan',
        highway: 'Çukurova Otoyolu (Adana-Gaziantep)',
        lat: 37.0260,
        lng: 35.8130,
        rates: [
            { vehicleType: 'CAR', amount: 36 },
            { vehicleType: 'MOTORCYCLE', amount: 15 },
            { vehicleType: 'VAN', amount: 40 },
            { vehicleType: 'BUS', amount: 56 },
            { vehicleType: 'TRUCK', amount: 89 },
        ],
    },
    {
        name: 'Toprakkale Gişeleri',
        location: 'Mersin Toprakkale',
        highway: 'Çukurova Otoyolu (Adana-Gaziantep)',
        lat: 37.0590,
        lng: 36.1440,
        rates: [
            { vehicleType: 'CAR', amount: 45 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 53 },
            { vehicleType: 'BUS', amount: 89 },
            { vehicleType: 'TRUCK', amount: 95 },
        ],
    },
    {
        name: 'Sakızgediği Gişeleri',
        location: 'Mersin Sakızgediği',
        highway: 'Çukurova Otoyolu (Adana-Gaziantep)',
        lat: 36.9750,
        lng: 36.1200,
        rates: [
            { vehicleType: 'CAR', amount: 45 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 53 },
            { vehicleType: 'BUS', amount: 89 },
            { vehicleType: 'TRUCK', amount: 95 },
        ],
    },
    {
        name: 'Osmaniye Gişeleri',
        location: 'Osmaniye',
        highway: 'Çukurova Otoyolu (Adana-Gaziantep)',
        lat: 37.0740,
        lng: 36.2480,
        rates: [
            { vehicleType: 'CAR', amount: 65 },
            { vehicleType: 'MOTORCYCLE', amount: 33 },
            { vehicleType: 'VAN', amount: 73 },
            { vehicleType: 'BUS', amount: 89 },
            { vehicleType: 'TRUCK', amount: 108 },
        ],
    },
    {
        name: 'Dörtyol Gişeleri',
        location: 'Hatay Dörtyol',
        highway: 'Çukurova Otoyolu (Adana-Gaziantep)',
        lat: 36.8570,
        lng: 36.2280,
        rates: [
            { vehicleType: 'CAR', amount: 53 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 65 },
            { vehicleType: 'BUS', amount: 89 },
            { vehicleType: 'TRUCK', amount: 95 },
        ],
    },
    {
        name: 'Payas Gişeleri',
        location: 'Hatay Payas',
        highway: 'Çukurova Otoyolu (Adana-Gaziantep)',
        lat: 36.7660,
        lng: 36.2570,
        rates: [
            { vehicleType: 'CAR', amount: 65 },
            { vehicleType: 'MOTORCYCLE', amount: 33 },
            { vehicleType: 'VAN', amount: 73 },
            { vehicleType: 'BUS', amount: 102 },
            { vehicleType: 'TRUCK', amount: 114 },
        ],
    },
    {
        name: 'İskenderun Gişeleri',
        location: 'Hatay İskenderun',
        highway: 'Çukurova Otoyolu (Adana-Gaziantep)',
        lat: 36.6000,
        lng: 36.1830,
        rates: [
            { vehicleType: 'CAR', amount: 65 },
            { vehicleType: 'MOTORCYCLE', amount: 33 },
            { vehicleType: 'VAN', amount: 73 },
            { vehicleType: 'BUS', amount: 102 },
            { vehicleType: 'TRUCK', amount: 114 },
        ],
    },
    {
        name: 'Bahçe Gişeleri',
        location: 'Hatay Bahçe',
        highway: 'Çukurova Otoyolu (Adana-Gaziantep)',
        lat: 37.1980,
        lng: 36.5770,
        rates: [
            { vehicleType: 'CAR', amount: 65 },
            { vehicleType: 'MOTORCYCLE', amount: 33 },
            { vehicleType: 'VAN', amount: 73 },
            { vehicleType: 'BUS', amount: 102 },
            { vehicleType: 'TRUCK', amount: 114 },
        ],
    },
    {
        name: 'Kömürler (Nurdağı) Gişeleri',
        location: 'Gaziantep Nurdağı',
        highway: 'Çukurova Otoyolu (Adana-Gaziantep)',
        lat: 37.1760,
        lng: 36.7290,
        rates: [
            { vehicleType: 'CAR', amount: 73 },
            { vehicleType: 'MOTORCYCLE', amount: 40 },
            { vehicleType: 'VAN', amount: 82 },
            { vehicleType: 'BUS', amount: 115 },
            { vehicleType: 'TRUCK', amount: 136 },
        ],
    },
    {
        name: 'Narlı Gişeleri',
        location: 'Gaziantep Narlı',
        highway: 'Çukurova Otoyolu (Adana-Gaziantep)',
        lat: 37.2990,
        lng: 37.2110,
        rates: [
            { vehicleType: 'CAR', amount: 102 },
            { vehicleType: 'MOTORCYCLE', amount: 45 },
            { vehicleType: 'VAN', amount: 120 },
            { vehicleType: 'BUS', amount: 156 },
            { vehicleType: 'TRUCK', amount: 177 },
        ],
    },
    {
        name: 'Gaziantep Batı Alın Gişeleri',
        location: 'Gaziantep Batı',
        highway: 'Çukurova Otoyolu (Adana-Gaziantep)',
        lat: 37.0840,
        lng: 37.3150,
        rates: [
            { vehicleType: 'CAR', amount: 102 },
            { vehicleType: 'MOTORCYCLE', amount: 45 },
            { vehicleType: 'VAN', amount: 120 },
            { vehicleType: 'BUS', amount: 156 },
            { vehicleType: 'TRUCK', amount: 205 },
        ],
    },

    // ==========================================
    // ÇUKUROVA OTOYOLU — Gaziantep-Şanlıurfa
    // KGM 2026 PDF 9: Tam rota 1.Sınıf = 102₺
    // ==========================================
    {
        name: 'Gaziantep Doğu Alın Gişeleri',
        location: 'Gaziantep Doğu',
        highway: 'Çukurova Otoyolu (Gaziantep-Şanlıurfa)',
        lat: 37.0950,
        lng: 37.4560,
        rates: [
            { vehicleType: 'CAR', amount: 102 },
            { vehicleType: 'MOTORCYCLE', amount: 45 },
            { vehicleType: 'VAN', amount: 120 },
            { vehicleType: 'BUS', amount: 156 },
            { vehicleType: 'TRUCK', amount: 177 },
        ],
    },
    {
        name: 'Nizip Gişeleri',
        location: 'Gaziantep Nizip',
        highway: 'Çukurova Otoyolu (Gaziantep-Şanlıurfa)',
        lat: 37.0100,
        lng: 37.7980,
        rates: [
            { vehicleType: 'CAR', amount: 45 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 53 },
            { vehicleType: 'BUS', amount: 89 },
            { vehicleType: 'TRUCK', amount: 95 },
        ],
    },
    {
        name: 'Birecik Gişeleri',
        location: 'Şanlıurfa Birecik',
        highway: 'Çukurova Otoyolu (Gaziantep-Şanlıurfa)',
        lat: 37.0290,
        lng: 37.9870,
        rates: [
            { vehicleType: 'CAR', amount: 59 },
            { vehicleType: 'MOTORCYCLE', amount: 33 },
            { vehicleType: 'VAN', amount: 75 },
            { vehicleType: 'BUS', amount: 94 },
            { vehicleType: 'TRUCK', amount: 114 },
        ],
    },
    {
        name: 'Suruç Gişeleri',
        location: 'Şanlıurfa Suruç',
        highway: 'Çukurova Otoyolu (Gaziantep-Şanlıurfa)',
        lat: 36.9780,
        lng: 38.5300,
        rates: [
            { vehicleType: 'CAR', amount: 75 },
            { vehicleType: 'MOTORCYCLE', amount: 40 },
            { vehicleType: 'VAN', amount: 95 },
            { vehicleType: 'BUS', amount: 114 },
            { vehicleType: 'TRUCK', amount: 136 },
        ],
    },
    {
        name: 'Şanlıurfa Gişeleri',
        location: 'Şanlıurfa',
        highway: 'Çukurova Otoyolu (Gaziantep-Şanlıurfa)',
        lat: 37.1674,
        lng: 38.7955,
        rates: [
            { vehicleType: 'CAR', amount: 102 },
            { vehicleType: 'MOTORCYCLE', amount: 45 },
            { vehicleType: 'VAN', amount: 120 },
            { vehicleType: 'BUS', amount: 156 },
            { vehicleType: 'TRUCK', amount: 177 },
        ],
    },

    // ==========================================
    // ÇUKUROVA OTOYOLU — Niğde-Mersin-Adana
    // KGM 2026 PDF 10
    // ==========================================
    {
        name: 'Niğde Güney Gişeleri',
        location: 'Niğde Güney',
        highway: 'Çukurova Otoyolu (Niğde-Mersin-Adana)',
        lat: 37.9180,
        lng: 34.6680,
        rates: [
            { vehicleType: 'CAR', amount: 197 },
            { vehicleType: 'MOTORCYCLE', amount: 94 },
            { vehicleType: 'VAN', amount: 237 },
            { vehicleType: 'BUS', amount: 305 },
            { vehicleType: 'TRUCK', amount: 370 },
        ],
    },
    {
        name: 'Niğde Kuzey Gişeleri',
        location: 'Niğde Kuzey',
        highway: 'Çukurova Otoyolu (Niğde-Mersin-Adana)',
        lat: 37.9720,
        lng: 34.6710,
        rates: [
            { vehicleType: 'CAR', amount: 36 },
            { vehicleType: 'MOTORCYCLE', amount: 15 },
            { vehicleType: 'VAN', amount: 40 },
            { vehicleType: 'BUS', amount: 45 },
            { vehicleType: 'TRUCK', amount: 56 },
        ],
    },
    {
        name: 'Gölcük Alın Gişeleri',
        location: 'Niğde Gölcük',
        highway: 'Çukurova Otoyolu (Niğde-Mersin-Adana)',
        lat: 37.8950,
        lng: 34.5830,
        rates: [
            { vehicleType: 'CAR', amount: 40 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 45 },
            { vehicleType: 'BUS', amount: 56 },
            { vehicleType: 'TRUCK', amount: 89 },
        ],
    },
    {
        name: 'Kemerhisar Gişeleri',
        location: 'Niğde Kemerhisar',
        highway: 'Çukurova Otoyolu (Niğde-Mersin-Adana)',
        lat: 37.8360,
        lng: 34.5140,
        rates: [
            { vehicleType: 'CAR', amount: 45 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 53 },
            { vehicleType: 'BUS', amount: 89 },
            { vehicleType: 'TRUCK', amount: 94 },
        ],
    },
    {
        name: 'Eminlik Alın Gişeleri',
        location: 'Niğde Eminlik',
        highway: 'Çukurova Otoyolu (Niğde-Mersin-Adana)',
        lat: 37.7250,
        lng: 34.4960,
        rates: [
            { vehicleType: 'CAR', amount: 45 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 53 },
            { vehicleType: 'BUS', amount: 89 },
            { vehicleType: 'TRUCK', amount: 103 },
        ],
    },
    {
        name: 'Pozantı (Kuzey) Gişeleri',
        location: 'Mersin Pozantı',
        highway: 'Çukurova Otoyolu (Niğde-Mersin-Adana)',
        lat: 37.4310,
        lng: 34.8750,
        rates: [
            { vehicleType: 'CAR', amount: 128 },
            { vehicleType: 'MOTORCYCLE', amount: 56 },
            { vehicleType: 'VAN', amount: 161 },
            { vehicleType: 'BUS', amount: 222 },
            { vehicleType: 'TRUCK', amount: 289 },
        ],
    },
    {
        name: 'Tekir Gişeleri',
        location: 'Mersin Tekir',
        highway: 'Çukurova Otoyolu (Niğde-Mersin-Adana)',
        lat: 37.2350,
        lng: 34.9350,
        rates: [
            { vehicleType: 'CAR', amount: 156 },
            { vehicleType: 'MOTORCYCLE', amount: 73 },
            { vehicleType: 'VAN', amount: 197 },
            { vehicleType: 'BUS', amount: 256 },
            { vehicleType: 'TRUCK', amount: 330 },
        ],
    },
    {
        name: 'Çamalan Gişeleri',
        location: 'Mersin Çamalan',
        highway: 'Çukurova Otoyolu (Niğde-Mersin-Adana)',
        lat: 37.1680,
        lng: 34.8970,
        rates: [
            { vehicleType: 'CAR', amount: 156 },
            { vehicleType: 'MOTORCYCLE', amount: 73 },
            { vehicleType: 'VAN', amount: 197 },
            { vehicleType: 'BUS', amount: 256 },
            { vehicleType: 'TRUCK', amount: 330 },
        ],
    },
    {
        name: 'Yenice Gişeleri',
        location: 'Mersin Yenice',
        highway: 'Çukurova Otoyolu (Niğde-Mersin-Adana)',
        lat: 37.0720,
        lng: 35.1680,
        rates: [
            { vehicleType: 'CAR', amount: 177 },
            { vehicleType: 'MOTORCYCLE', amount: 82 },
            { vehicleType: 'VAN', amount: 222 },
            { vehicleType: 'BUS', amount: 282 },
            { vehicleType: 'TRUCK', amount: 345 },
        ],
    },
    {
        name: 'Adana Batı Alın Gişeleri',
        location: 'Adana Batı',
        highway: 'Çukurova Otoyolu (Niğde-Mersin-Adana)',
        lat: 36.9990,
        lng: 35.3010,
        rates: [
            { vehicleType: 'CAR', amount: 177 },
            { vehicleType: 'MOTORCYCLE', amount: 82 },
            { vehicleType: 'VAN', amount: 222 },
            { vehicleType: 'BUS', amount: 282 },
            { vehicleType: 'TRUCK', amount: 345 },
        ],
    },
    {
        name: 'Tarsus Gişeleri',
        location: 'Mersin Tarsus',
        highway: 'Çukurova Otoyolu (Niğde-Mersin-Adana)',
        lat: 36.9000,
        lng: 34.9020,
        rates: [
            { vehicleType: 'CAR', amount: 177 },
            { vehicleType: 'MOTORCYCLE', amount: 82 },
            { vehicleType: 'VAN', amount: 222 },
            { vehicleType: 'BUS', amount: 282 },
            { vehicleType: 'TRUCK', amount: 345 },
        ],
    },
    {
        name: 'Tarsus OSB Gişeleri',
        location: 'Mersin Tarsus OSB',
        highway: 'Çukurova Otoyolu (Niğde-Mersin-Adana)',
        lat: 36.8780,
        lng: 34.8670,
        rates: [
            { vehicleType: 'CAR', amount: 181 },
            { vehicleType: 'MOTORCYCLE', amount: 82 },
            { vehicleType: 'VAN', amount: 223 },
            { vehicleType: 'BUS', amount: 285 },
            { vehicleType: 'TRUCK', amount: 350 },
        ],
    },
    {
        name: 'Mersin Alın Gişeleri',
        location: 'Mersin',
        highway: 'Çukurova Otoyolu (Niğde-Mersin-Adana)',
        lat: 36.8230,
        lng: 34.6420,
        rates: [
            { vehicleType: 'CAR', amount: 184 },
            { vehicleType: 'MOTORCYCLE', amount: 82 },
            { vehicleType: 'VAN', amount: 223 },
            { vehicleType: 'BUS', amount: 289 },
            { vehicleType: 'TRUCK', amount: 363 },
        ],
    },

    // ==========================================
    // YSS KUZEY ÇEVRE YOLU — Fenertepe → Kurnaköy
    // KGM 2026 PDF 13: Tam rota 1.Sınıf = 510₺
    // ==========================================
    {
        name: 'Fenertepe Gişeleri',
        location: 'İstanbul Fenertepe',
        highway: 'YSS Kuzey Çevre Yolu',
        lat: 41.1750,
        lng: 28.8510,
        rates: [
            { vehicleType: 'CAR', amount: 510 },
            { vehicleType: 'MOTORCYCLE', amount: 115 },
            { vehicleType: 'VAN', amount: 590 },
            { vehicleType: 'BUS', amount: 790 },
            { vehicleType: 'TRUCK', amount: 990 },
        ],
    },
    {
        name: 'Işıklar Gişeleri',
        location: 'İstanbul Işıklar',
        highway: 'YSS Kuzey Çevre Yolu',
        lat: 41.1900,
        lng: 28.9300,
        rates: [
            { vehicleType: 'CAR', amount: 90 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 130 },
            { vehicleType: 'BUS', amount: 160 },
            { vehicleType: 'TRUCK', amount: 200 },
        ],
    },
    {
        name: 'Ağaçlı Gişeleri',
        location: 'İstanbul Ağaçlı',
        highway: 'YSS Kuzey Çevre Yolu',
        lat: 41.2100,
        lng: 28.9850,
        rates: [
            { vehicleType: 'CAR', amount: 90 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 130 },
            { vehicleType: 'BUS', amount: 160 },
            { vehicleType: 'TRUCK', amount: 200 },
        ],
    },
    {
        name: 'Odayeri Gişeleri',
        location: 'İstanbul Odayeri',
        highway: 'YSS Kuzey Çevre Yolu',
        lat: 41.2250,
        lng: 29.0200,
        rates: [
            { vehicleType: 'CAR', amount: 100 },
            { vehicleType: 'MOTORCYCLE', amount: 25 },
            { vehicleType: 'VAN', amount: 145 },
            { vehicleType: 'BUS', amount: 180 },
            { vehicleType: 'TRUCK', amount: 225 },
        ],
    },
    {
        name: 'Uskumruköy Gişeleri',
        location: 'İstanbul Uskumruköy',
        highway: 'YSS Kuzey Çevre Yolu',
        lat: 41.1820,
        lng: 29.0980,
        rates: [
            { vehicleType: 'CAR', amount: 190 },
            { vehicleType: 'MOTORCYCLE', amount: 40 },
            { vehicleType: 'VAN', amount: 275 },
            { vehicleType: 'BUS', amount: 340 },
            { vehicleType: 'TRUCK', amount: 430 },
        ],
    },
    {
        name: 'Riva Gişeleri',
        location: 'İstanbul Riva',
        highway: 'YSS Kuzey Çevre Yolu',
        lat: 41.2020,
        lng: 29.2410,
        rates: [
            { vehicleType: 'CAR', amount: 345 },
            { vehicleType: 'MOTORCYCLE', amount: 75 },
            { vehicleType: 'VAN', amount: 495 },
            { vehicleType: 'BUS', amount: 615 },
            { vehicleType: 'TRUCK', amount: 770 },
        ],
    },
    {
        name: 'Hüseyinli Gişeleri',
        location: 'İstanbul Hüseyinli',
        highway: 'YSS Kuzey Çevre Yolu',
        lat: 41.1670,
        lng: 29.3500,
        rates: [
            { vehicleType: 'CAR', amount: 410 },
            { vehicleType: 'MOTORCYCLE', amount: 85 },
            { vehicleType: 'VAN', amount: 585 },
            { vehicleType: 'BUS', amount: 730 },
            { vehicleType: 'TRUCK', amount: 915 },
        ],
    },
    {
        name: 'Reşadiye Gişeleri',
        location: 'İstanbul Reşadiye',
        highway: 'YSS Kuzey Çevre Yolu',
        lat: 41.0960,
        lng: 29.4100,
        rates: [
            { vehicleType: 'CAR', amount: 460 },
            { vehicleType: 'MOTORCYCLE', amount: 100 },
            { vehicleType: 'VAN', amount: 655 },
            { vehicleType: 'BUS', amount: 820 },
            { vehicleType: 'TRUCK', amount: 1025 },
        ],
    },
    {
        name: 'Alemdağ Gişeleri',
        location: 'İstanbul Alemdağ',
        highway: 'YSS Kuzey Çevre Yolu',
        lat: 41.0480,
        lng: 29.2640,
        rates: [
            { vehicleType: 'CAR', amount: 460 },
            { vehicleType: 'MOTORCYCLE', amount: 100 },
            { vehicleType: 'VAN', amount: 655 },
            { vehicleType: 'BUS', amount: 820 },
            { vehicleType: 'TRUCK', amount: 1025 },
        ],
    },
    {
        name: 'Paşaköy Gişeleri',
        location: 'İstanbul Paşaköy',
        highway: 'YSS Kuzey Çevre Yolu',
        lat: 41.0210,
        lng: 29.1800,
        rates: [
            { vehicleType: 'CAR', amount: 460 },
            { vehicleType: 'MOTORCYCLE', amount: 100 },
            { vehicleType: 'VAN', amount: 655 },
            { vehicleType: 'BUS', amount: 820 },
            { vehicleType: 'TRUCK', amount: 1025 },
        ],
    },
    {
        name: 'Mecidiye Gişeleri',
        location: 'İstanbul Mecidiye',
        highway: 'YSS Kuzey Çevre Yolu',
        lat: 41.0360,
        lng: 29.1060,
        rates: [
            { vehicleType: 'CAR', amount: 510 },
            { vehicleType: 'MOTORCYCLE', amount: 115 },
            { vehicleType: 'VAN', amount: 735 },
            { vehicleType: 'BUS', amount: 920 },
            { vehicleType: 'TRUCK', amount: 1150 },
        ],
    },
    {
        name: 'Kurnaköy Gişeleri',
        location: 'İstanbul Kurnaköy',
        highway: 'YSS Kuzey Çevre Yolu',
        lat: 41.0620,
        lng: 29.0420,
        rates: [
            { vehicleType: 'CAR', amount: 510 },
            { vehicleType: 'MOTORCYCLE', amount: 115 },
            { vehicleType: 'VAN', amount: 735 },
            { vehicleType: 'BUS', amount: 920 },
            { vehicleType: 'TRUCK', amount: 1150 },
        ],
    },

    // ==========================================
    // KMO AVRUPA OTOYOLU — Kınalı → Odayeri
    // KGM 2026 PDF 14: Tam rota 1.Sınıf = 220₺
    // ==========================================
    {
        name: 'Kınalı Gişeleri (KMO Avrupa)',
        location: 'İstanbul Kınalı',
        highway: 'KMO Avrupa Otoyolu (Kınalı-Odayeri)',
        lat: 41.1850,
        lng: 28.3020,
        rates: [
            { vehicleType: 'CAR', amount: 220 },
            { vehicleType: 'MOTORCYCLE', amount: 165 },
            { vehicleType: 'VAN', amount: 350 },
            { vehicleType: 'BUS', amount: 410 },
            { vehicleType: 'TRUCK', amount: 535 },
        ],
    },
    {
        name: 'Silivri Gişeleri (KMO Avrupa)',
        location: 'İstanbul Silivri',
        highway: 'KMO Avrupa Otoyolu (Kınalı-Odayeri)',
        lat: 41.0670,
        lng: 28.7320,
        rates: [
            { vehicleType: 'CAR', amount: 55 },
            { vehicleType: 'MOTORCYCLE', amount: 55 },
            { vehicleType: 'VAN', amount: 100 },
            { vehicleType: 'BUS', amount: 100 },
            { vehicleType: 'TRUCK', amount: 140 },
        ],
    },
    {
        name: 'Çatalca Gişeleri (KMO Avrupa)',
        location: 'İstanbul Çatalca',
        highway: 'KMO Avrupa Otoyolu (Kınalı-Odayeri)',
        lat: 41.1380,
        lng: 28.4630,
        rates: [
            { vehicleType: 'CAR', amount: 140 },
            { vehicleType: 'MOTORCYCLE', amount: 90 },
            { vehicleType: 'VAN', amount: 190 },
            { vehicleType: 'BUS', amount: 220 },
            { vehicleType: 'TRUCK', amount: 295 },
        ],
    },
    {
        name: 'Nakkaş Gişeleri',
        location: 'İstanbul Nakkaş',
        highway: 'KMO Avrupa Otoyolu (Kınalı-Odayeri)',
        lat: 41.1550,
        lng: 28.5500,
        rates: [
            { vehicleType: 'CAR', amount: 165 },
            { vehicleType: 'MOTORCYCLE', amount: 100 },
            { vehicleType: 'VAN', amount: 250 },
            { vehicleType: 'BUS', amount: 265 },
            { vehicleType: 'TRUCK', amount: 365 },
        ],
    },
    {
        name: 'Yassiören Gişeleri',
        location: 'İstanbul Yassiören',
        highway: 'KMO Avrupa Otoyolu (Kınalı-Odayeri)',
        lat: 41.2050,
        lng: 28.8500,
        rates: [
            { vehicleType: 'CAR', amount: 190 },
            { vehicleType: 'MOTORCYCLE', amount: 140 },
            { vehicleType: 'VAN', amount: 265 },
            { vehicleType: 'BUS', amount: 315 },
            { vehicleType: 'TRUCK', amount: 415 },
        ],
    },
    {
        name: 'Tayakadin Gişeleri',
        location: 'İstanbul Tayakadin',
        highway: 'KMO Avrupa Otoyolu (Kınalı-Odayeri)',
        lat: 41.2450,
        lng: 28.9700,
        rates: [
            { vehicleType: 'CAR', amount: 220 },
            { vehicleType: 'MOTORCYCLE', amount: 165 },
            { vehicleType: 'VAN', amount: 315 },
            { vehicleType: 'BUS', amount: 410 },
            { vehicleType: 'TRUCK', amount: 510 },
        ],
    },
    {
        name: 'Fatih Gişeleri (KMO Avrupa)',
        location: 'İstanbul Fatih',
        highway: 'KMO Avrupa Otoyolu (Kınalı-Odayeri)',
        lat: 41.2700,
        lng: 29.1950,
        rates: [
            { vehicleType: 'CAR', amount: 220 },
            { vehicleType: 'MOTORCYCLE', amount: 165 },
            { vehicleType: 'VAN', amount: 350 },
            { vehicleType: 'BUS', amount: 415 },
            { vehicleType: 'TRUCK', amount: 535 },
        ],
    },

    // ==========================================
    // KMO ANADOLU OTOYOLU — Kurtköy → Akyazi
    // KGM 2026 PDF 15: Tam rota 1.Sınıf = 510₺
    // ==========================================
    {
        name: 'Kurtköy 2 Gişeleri',
        location: 'İstanbul Kurtköy',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.9010,
        lng: 29.3180,
        rates: [
            { vehicleType: 'CAR', amount: 510 },
            { vehicleType: 'MOTORCYCLE', amount: 350 },
            { vehicleType: 'VAN', amount: 795 },
            { vehicleType: 'BUS', amount: 930 },
            { vehicleType: 'TRUCK', amount: 1210 },
        ],
    },
    {
        name: 'İstanbulpark Gişeleri',
        location: 'İstanbul İstanbulpark',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.9160,
        lng: 29.5800,
        rates: [
            { vehicleType: 'CAR', amount: 55 },
            { vehicleType: 'MOTORCYCLE', amount: 55 },
            { vehicleType: 'VAN', amount: 90 },
            { vehicleType: 'BUS', amount: 90 },
            { vehicleType: 'TRUCK', amount: 100 },
        ],
    },
    {
        name: 'Balçık Gişeleri',
        location: 'Kocaeli Balçık',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.8200,
        lng: 29.6500,
        rates: [
            { vehicleType: 'CAR', amount: 90 },
            { vehicleType: 'MOTORCYCLE', amount: 55 },
            { vehicleType: 'VAN', amount: 140 },
            { vehicleType: 'BUS', amount: 140 },
            { vehicleType: 'TRUCK', amount: 190 },
        ],
    },
    {
        name: 'Mermerciler Gişeleri',
        location: 'Kocaeli Mermerciler',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.7950,
        lng: 29.7100,
        rates: [
            { vehicleType: 'CAR', amount: 100 },
            { vehicleType: 'MOTORCYCLE', amount: 90 },
            { vehicleType: 'VAN', amount: 165 },
            { vehicleType: 'BUS', amount: 190 },
            { vehicleType: 'TRUCK', amount: 250 },
        ],
    },
    {
        name: 'Sevindikli Gişeleri',
        location: 'Kocaeli Sevindikli',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.7450,
        lng: 29.8800,
        rates: [
            { vehicleType: 'CAR', amount: 190 },
            { vehicleType: 'MOTORCYCLE', amount: 140 },
            { vehicleType: 'VAN', amount: 265 },
            { vehicleType: 'BUS', amount: 315 },
            { vehicleType: 'TRUCK', amount: 410 },
        ],
    },
    {
        name: 'İlimtepe Gişeleri',
        location: 'Kocaeli İlimtepe',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.7100,
        lng: 29.9600,
        rates: [
            { vehicleType: 'CAR', amount: 190 },
            { vehicleType: 'MOTORCYCLE', amount: 140 },
            { vehicleType: 'VAN', amount: 265 },
            { vehicleType: 'BUS', amount: 315 },
            { vehicleType: 'TRUCK', amount: 415 },
        ],
    },
    {
        name: 'İzmit Kuzey Gişeleri',
        location: 'Kocaeli İzmit Kuzey',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.7230,
        lng: 29.9800,
        rates: [
            { vehicleType: 'CAR', amount: 265 },
            { vehicleType: 'MOTORCYCLE', amount: 190 },
            { vehicleType: 'VAN', amount: 415 },
            { vehicleType: 'BUS', amount: 510 },
            { vehicleType: 'TRUCK', amount: 670 },
        ],
    },
    {
        name: 'İzmit Doğu Gişeleri',
        location: 'Kocaeli İzmit Doğu',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.7650,
        lng: 29.9550,
        rates: [
            { vehicleType: 'CAR', amount: 265 },
            { vehicleType: 'MOTORCYCLE', amount: 190 },
            { vehicleType: 'VAN', amount: 415 },
            { vehicleType: 'BUS', amount: 510 },
            { vehicleType: 'TRUCK', amount: 670 },
        ],
    },
    {
        name: 'Akmeşe Gişeleri',
        location: 'Sakarya Akmeşe',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.8000,
        lng: 30.0500,
        rates: [
            { vehicleType: 'CAR', amount: 350 },
            { vehicleType: 'MOTORCYCLE', amount: 250 },
            { vehicleType: 'VAN', amount: 535 },
            { vehicleType: 'BUS', amount: 635 },
            { vehicleType: 'TRUCK', amount: 840 },
        ],
    },
    {
        name: 'Adapazarı-1 Gişeleri',
        location: 'Sakarya Adapazarı-1',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.6750,
        lng: 30.3980,
        rates: [
            { vehicleType: 'CAR', amount: 410 },
            { vehicleType: 'MOTORCYCLE', amount: 265 },
            { vehicleType: 'VAN', amount: 615 },
            { vehicleType: 'BUS', amount: 720 },
            { vehicleType: 'TRUCK', amount: 945 },
        ],
    },
    {
        name: 'Adapazarı-2 Gişeleri',
        location: 'Sakarya Adapazarı-2',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.6720,
        lng: 30.4150,
        rates: [
            { vehicleType: 'CAR', amount: 410 },
            { vehicleType: 'MOTORCYCLE', amount: 295 },
            { vehicleType: 'VAN', amount: 635 },
            { vehicleType: 'BUS', amount: 740 },
            { vehicleType: 'TRUCK', amount: 985 },
        ],
    },
    {
        name: 'Karasu Gişeleri',
        location: 'Sakarya Karasu',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.6850,
        lng: 30.4800,
        rates: [
            { vehicleType: 'CAR', amount: 415 },
            { vehicleType: 'MOTORCYCLE', amount: 295 },
            { vehicleType: 'VAN', amount: 670 },
            { vehicleType: 'BUS', amount: 795 },
            { vehicleType: 'TRUCK', amount: 1055 },
        ],
    },
    {
        name: 'KMO Akyazi Gişeleri',
        location: 'Sakarya Akyazi',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.6880,
        lng: 30.6250,
        rates: [
            { vehicleType: 'CAR', amount: 475 },
            { vehicleType: 'MOTORCYCLE', amount: 315 },
            { vehicleType: 'VAN', amount: 740 },
            { vehicleType: 'BUS', amount: 885 },
            { vehicleType: 'TRUCK', amount: 1150 },
        ],
    },
    {
        name: 'TEM Akyazi Gişeleri',
        location: 'Sakarya Akyazi (TEM)',
        highway: 'KMO Anadolu Otoyolu (Kurtköy-Akyazi)',
        lat: 40.6900,
        lng: 30.6400,
        rates: [
            { vehicleType: 'CAR', amount: 510 },
            { vehicleType: 'MOTORCYCLE', amount: 350 },
            { vehicleType: 'VAN', amount: 795 },
            { vehicleType: 'BUS', amount: 930 },
            { vehicleType: 'TRUCK', amount: 1210 },
        ],
    },

    // ==========================================
    // MENEMEN-ALİAĞA-ÇANDARLI OTOYOLU
    // KGM 2026 PDF 16: Tam rota 1.Sınıf = 205₺
    // ==========================================
    {
        name: 'Menemen Gişeleri',
        location: 'İzmir Menemen',
        highway: 'Menemen-Aliağa-Çandarlı Otoyolu',
        lat: 38.5970,
        lng: 27.0640,
        rates: [
            { vehicleType: 'CAR', amount: 205 },
            { vehicleType: 'MOTORCYCLE', amount: 50 },
            { vehicleType: 'VAN', amount: 340 },
            { vehicleType: 'BUS', amount: 400 },
            { vehicleType: 'TRUCK', amount: 525 },
        ],
    },
    {
        name: 'Eskifoça Gişeleri',
        location: 'İzmir Eskifoça',
        highway: 'Menemen-Aliağa-Çandarlı Otoyolu',
        lat: 38.6600,
        lng: 26.9060,
        rates: [
            { vehicleType: 'CAR', amount: 80 },
            { vehicleType: 'MOTORCYCLE', amount: 20 },
            { vehicleType: 'VAN', amount: 130 },
            { vehicleType: 'BUS', amount: 150 },
            { vehicleType: 'TRUCK', amount: 200 },
        ],
    },
    {
        name: 'Yenifoça Gişeleri',
        location: 'İzmir Yenifoça',
        highway: 'Menemen-Aliağa-Çandarlı Otoyolu',
        lat: 38.7260,
        lng: 26.8690,
        rates: [
            { vehicleType: 'CAR', amount: 100 },
            { vehicleType: 'MOTORCYCLE', amount: 25 },
            { vehicleType: 'VAN', amount: 165 },
            { vehicleType: 'BUS', amount: 195 },
            { vehicleType: 'TRUCK', amount: 255 },
        ],
    },
    {
        name: 'Aliağa Petkim Gişeleri',
        location: 'İzmir Aliağa Petkim',
        highway: 'Menemen-Aliağa-Çandarlı Otoyolu',
        lat: 38.8030,
        lng: 26.9590,
        rates: [
            { vehicleType: 'CAR', amount: 120 },
            { vehicleType: 'MOTORCYCLE', amount: 30 },
            { vehicleType: 'VAN', amount: 190 },
            { vehicleType: 'BUS', amount: 220 },
            { vehicleType: 'TRUCK', amount: 295 },
        ],
    },
    {
        name: 'Aliağa OSB Gişeleri',
        location: 'İzmir Aliağa OSB',
        highway: 'Menemen-Aliağa-Çandarlı Otoyolu',
        lat: 38.8480,
        lng: 27.0090,
        rates: [
            { vehicleType: 'CAR', amount: 140 },
            { vehicleType: 'MOTORCYCLE', amount: 40 },
            { vehicleType: 'VAN', amount: 220 },
            { vehicleType: 'BUS', amount: 265 },
            { vehicleType: 'TRUCK', amount: 350 },
        ],
    },
    {
        name: 'Yenişakran Gişeleri',
        location: 'İzmir Yenişakran',
        highway: 'Menemen-Aliağa-Çandarlı Otoyolu',
        lat: 38.9140,
        lng: 27.0720,
        rates: [
            { vehicleType: 'CAR', amount: 175 },
            { vehicleType: 'MOTORCYCLE', amount: 45 },
            { vehicleType: 'VAN', amount: 280 },
            { vehicleType: 'BUS', amount: 335 },
            { vehicleType: 'TRUCK', amount: 440 },
        ],
    },
    {
        name: 'Çandarlı Gişeleri',
        location: 'İzmir Çandarlı',
        highway: 'Menemen-Aliağa-Çandarlı Otoyolu',
        lat: 38.9280,
        lng: 27.0540,
        rates: [
            { vehicleType: 'CAR', amount: 205 },
            { vehicleType: 'MOTORCYCLE', amount: 50 },
            { vehicleType: 'VAN', amount: 340 },
            { vehicleType: 'BUS', amount: 400 },
            { vehicleType: 'TRUCK', amount: 525 },
        ],
    },

    // ==========================================
    // ANKARA-NİĞDE OTOYOLU
    // KGM 2026 PDF 17: Tam rota 1.Sınıf = 740₺
    // ==========================================
    {
        name: 'Ankara Alın Gişeleri',
        location: 'Ankara Alın',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 39.8230,
        lng: 32.5540,
        rates: [
            { vehicleType: 'CAR', amount: 740 },
            { vehicleType: 'MOTORCYCLE', amount: 250 },
            { vehicleType: 'VAN', amount: 840 },
            { vehicleType: 'BUS', amount: 1010 },
            { vehicleType: 'TRUCK', amount: 1300 },
        ],
    },
    {
        name: 'Karagedik Gişeleri',
        location: 'Ankara Karagedik',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 39.7180,
        lng: 32.7200,
        rates: [
            { vehicleType: 'CAR', amount: 90 },
            { vehicleType: 'MOTORCYCLE', amount: 30 },
            { vehicleType: 'VAN', amount: 100 },
            { vehicleType: 'BUS', amount: 140 },
            { vehicleType: 'TRUCK', amount: 190 },
        ],
    },
    {
        name: 'Ahiboz Gişeleri',
        location: 'Ankara Ahiboz',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 39.6100,
        lng: 32.8500,
        rates: [
            { vehicleType: 'CAR', amount: 100 },
            { vehicleType: 'MOTORCYCLE', amount: 35 },
            { vehicleType: 'VAN', amount: 110 },
            { vehicleType: 'BUS', amount: 155 },
            { vehicleType: 'TRUCK', amount: 210 },
        ],
    },
    {
        name: 'Emirler Gişeleri',
        location: 'Ankara Emirler',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 39.4500,
        lng: 32.9800,
        rates: [
            { vehicleType: 'CAR', amount: 190 },
            { vehicleType: 'MOTORCYCLE', amount: 65 },
            { vehicleType: 'VAN', amount: 210 },
            { vehicleType: 'BUS', amount: 295 },
            { vehicleType: 'TRUCK', amount: 400 },
        ],
    },
    {
        name: 'Kulu-Kırıkkale Gişeleri',
        location: 'Ankara Kulu',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 39.3200,
        lng: 33.3500,
        rates: [
            { vehicleType: 'CAR', amount: 220 },
            { vehicleType: 'MOTORCYCLE', amount: 75 },
            { vehicleType: 'VAN', amount: 240 },
            { vehicleType: 'BUS', amount: 340 },
            { vehicleType: 'TRUCK', amount: 460 },
        ],
    },
    {
        name: 'Acıkuyu Gişeleri',
        location: 'Niğde Acıkuyu',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 38.9500,
        lng: 33.8200,
        rates: [
            { vehicleType: 'CAR', amount: 315 },
            { vehicleType: 'MOTORCYCLE', amount: 110 },
            { vehicleType: 'VAN', amount: 345 },
            { vehicleType: 'BUS', amount: 480 },
            { vehicleType: 'TRUCK', amount: 650 },
        ],
    },
    {
        name: 'Evren-Sarıyahşi Gişeleri',
        location: 'Niğde Evren',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 38.7800,
        lng: 34.2100,
        rates: [
            { vehicleType: 'CAR', amount: 410 },
            { vehicleType: 'MOTORCYCLE', amount: 145 },
            { vehicleType: 'VAN', amount: 450 },
            { vehicleType: 'BUS', amount: 625 },
            { vehicleType: 'TRUCK', amount: 850 },
        ],
    },
    {
        name: 'Ağaçören Gişeleri',
        location: 'Niğde Ağaçören',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 38.5600,
        lng: 34.3200,
        rates: [
            { vehicleType: 'CAR', amount: 450 },
            { vehicleType: 'MOTORCYCLE', amount: 160 },
            { vehicleType: 'VAN', amount: 495 },
            { vehicleType: 'BUS', amount: 685 },
            { vehicleType: 'TRUCK', amount: 930 },
        ],
    },
    {
        name: 'Kırşehir Gişeleri',
        location: 'Kırşehir',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 39.1400,
        lng: 34.1600,
        rates: [
            { vehicleType: 'CAR', amount: 535 },
            { vehicleType: 'MOTORCYCLE', amount: 190 },
            { vehicleType: 'VAN', amount: 585 },
            { vehicleType: 'BUS', amount: 815 },
            { vehicleType: 'TRUCK', amount: 1100 },
        ],
    },
    {
        name: 'Ortaköy Gişeleri',
        location: 'Niğde Ortaköy',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 38.3200,
        lng: 34.4500,
        rates: [
            { vehicleType: 'CAR', amount: 510 },
            { vehicleType: 'MOTORCYCLE', amount: 180 },
            { vehicleType: 'VAN', amount: 560 },
            { vehicleType: 'BUS', amount: 775 },
            { vehicleType: 'TRUCK', amount: 1050 },
        ],
    },
    {
        name: 'Alayhan Gişeleri',
        location: 'Niğde Alayhan',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 38.0900,
        lng: 34.5800,
        rates: [
            { vehicleType: 'CAR', amount: 615 },
            { vehicleType: 'MOTORCYCLE', amount: 220 },
            { vehicleType: 'VAN', amount: 675 },
            { vehicleType: 'BUS', amount: 930 },
            { vehicleType: 'TRUCK', amount: 1260 },
        ],
    },
    {
        name: 'Derinkuyu Gişeleri',
        location: 'Niğde Derinkuyu',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 38.3650,
        lng: 34.5180,
        rates: [
            { vehicleType: 'CAR', amount: 670 },
            { vehicleType: 'MOTORCYCLE', amount: 240 },
            { vehicleType: 'VAN', amount: 735 },
            { vehicleType: 'BUS', amount: 1010 },
            { vehicleType: 'TRUCK', amount: 1370 },
        ],
    },
    {
        name: 'Çiftlik Gişeleri',
        location: 'Niğde Çiftlik',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 37.9820,
        lng: 34.5720,
        rates: [
            { vehicleType: 'CAR', amount: 680 },
            { vehicleType: 'MOTORCYCLE', amount: 245 },
            { vehicleType: 'VAN', amount: 745 },
            { vehicleType: 'BUS', amount: 1025 },
            { vehicleType: 'TRUCK', amount: 1390 },
        ],
    },
    {
        name: 'Niğde Alın Gişeleri',
        location: 'Niğde Alın',
        highway: 'Ankara-Niğde Otoyolu',
        lat: 37.8750,
        lng: 34.6050,
        rates: [
            { vehicleType: 'CAR', amount: 740 },
            { vehicleType: 'MOTORCYCLE', amount: 250 },
            { vehicleType: 'VAN', amount: 840 },
            { vehicleType: 'BUS', amount: 1010 },
            { vehicleType: 'TRUCK', amount: 1300 },
        ],
    },

    // ==========================================
    // MALKARA-ÇANAKKALE OTOYOLU
    // KGM 2026 PDF 18: Tam rota 1.Sınıf = 1260₺
    // ==========================================
    {
        name: 'Malkara Gişeleri',
        location: 'Tekirdağ Malkara',
        highway: 'Malkara-Çanakkale Otoyolu',
        lat: 41.8850,
        lng: 26.9000,
        rates: [
            { vehicleType: 'CAR', amount: 1260 },
            { vehicleType: 'MOTORCYCLE', amount: 315 },
            { vehicleType: 'VAN', amount: 1665 },
            { vehicleType: 'BUS', amount: 2740 },
            { vehicleType: 'TRUCK', amount: 3155 },
        ],
    },
    {
        name: 'Kavakköy Gişeleri',
        location: 'Çanakkale Kavakköy',
        highway: 'Malkara-Çanakkale Otoyolu',
        lat: 40.5000,
        lng: 26.7850,
        rates: [
            { vehicleType: 'CAR', amount: 150 },
            { vehicleType: 'MOTORCYCLE', amount: 35 },
            { vehicleType: 'VAN', amount: 195 },
            { vehicleType: 'BUS', amount: 320 },
            { vehicleType: 'TRUCK', amount: 370 },
        ],
    },
    {
        name: 'Gelibolu Kuzey Gişeleri',
        location: 'Çanakkale Gelibolu Kuzey',
        highway: 'Malkara-Çanakkale Otoyolu',
        lat: 40.4100,
        lng: 26.6750,
        rates: [
            { vehicleType: 'CAR', amount: 220 },
            { vehicleType: 'MOTORCYCLE', amount: 50 },
            { vehicleType: 'VAN', amount: 285 },
            { vehicleType: 'BUS', amount: 470 },
            { vehicleType: 'TRUCK', amount: 540 },
        ],
    },
    {
        name: 'Gelibolu Güney Gişeleri',
        location: 'Çanakkale Gelibolu Güney',
        highway: 'Malkara-Çanakkale Otoyolu',
        lat: 40.3500,
        lng: 26.6700,
        rates: [
            { vehicleType: 'CAR', amount: 270 },
            { vehicleType: 'MOTORCYCLE', amount: 65 },
            { vehicleType: 'VAN', amount: 350 },
            { vehicleType: 'BUS', amount: 575 },
            { vehicleType: 'TRUCK', amount: 660 },
        ],
    },
    {
        name: '1915 Çanakkale Köprüsü (Malkara Rotası)',
        location: 'Çanakkale 1915 Köprüsü',
        highway: 'Malkara-Çanakkale Otoyolu',
        lat: 40.3372,
        lng: 26.6650,
        rates: [
            { vehicleType: 'CAR', amount: 1260 },
            { vehicleType: 'MOTORCYCLE', amount: 315 },
            { vehicleType: 'VAN', amount: 1665 },
            { vehicleType: 'BUS', amount: 2740 },
            { vehicleType: 'TRUCK', amount: 3155 },
        ],
    },

    // ==========================================
    // AYDIN-DENİZLİ OTOYOLU
    // KGM 2026 PDF 19: Tam rota 1.Sınıf = 500₺
    // ==========================================
    {
        name: 'Aydın Alın Gişeleri',
        location: 'Aydın Alın',
        highway: 'Aydın-Denizli Otoyolu',
        lat: 37.8480,
        lng: 27.8650,
        rates: [
            { vehicleType: 'CAR', amount: 500 },
            { vehicleType: 'MOTORCYCLE', amount: 100 },
            { vehicleType: 'VAN', amount: 635 },
            { vehicleType: 'BUS', amount: 760 },
            { vehicleType: 'TRUCK', amount: 910 },
        ],
    },
    {
        name: 'Köşk Gişeleri',
        location: 'Aydın Köşk',
        highway: 'Aydın-Denizli Otoyolu',
        lat: 37.8100,
        lng: 27.8900,
        rates: [
            { vehicleType: 'CAR', amount: 75 },
            { vehicleType: 'MOTORCYCLE', amount: 15 },
            { vehicleType: 'VAN', amount: 95 },
            { vehicleType: 'BUS', amount: 115 },
            { vehicleType: 'TRUCK', amount: 140 },
        ],
    },
    {
        name: 'Yeni Pazar Gişeleri',
        location: 'Aydın Yeni Pazar',
        highway: 'Aydın-Denizli Otoyolu',
        lat: 37.8050,
        lng: 27.9400,
        rates: [
            { vehicleType: 'CAR', amount: 130 },
            { vehicleType: 'MOTORCYCLE', amount: 25 },
            { vehicleType: 'VAN', amount: 165 },
            { vehicleType: 'BUS', amount: 200 },
            { vehicleType: 'TRUCK', amount: 240 },
        ],
    },
    {
        name: 'Nazilli Gişeleri',
        location: 'Aydın Nazilli',
        highway: 'Aydın-Denizli Otoyolu',
        lat: 37.9110,
        lng: 28.3090,
        rates: [
            { vehicleType: 'CAR', amount: 165 },
            { vehicleType: 'MOTORCYCLE', amount: 30 },
            { vehicleType: 'VAN', amount: 210 },
            { vehicleType: 'BUS', amount: 250 },
            { vehicleType: 'TRUCK', amount: 300 },
        ],
    },
    {
        name: 'Kuyucak Gişeleri',
        location: 'Aydın Kuyucak',
        highway: 'Aydın-Denizli Otoyolu',
        lat: 37.8570,
        lng: 28.6200,
        rates: [
            { vehicleType: 'CAR', amount: 225 },
            { vehicleType: 'MOTORCYCLE', amount: 45 },
            { vehicleType: 'VAN', amount: 285 },
            { vehicleType: 'BUS', amount: 340 },
            { vehicleType: 'TRUCK', amount: 410 },
        ],
    },
    {
        name: 'Buharkent Gişeleri',
        location: 'Denizli Buharkent',
        highway: 'Aydın-Denizli Otoyolu',
        lat: 37.6600,
        lng: 28.9050,
        rates: [
            { vehicleType: 'CAR', amount: 300 },
            { vehicleType: 'MOTORCYCLE', amount: 60 },
            { vehicleType: 'VAN', amount: 380 },
            { vehicleType: 'BUS', amount: 455 },
            { vehicleType: 'TRUCK', amount: 545 },
        ],
    },
    {
        name: 'Sarayköy Gişeleri',
        location: 'Denizli Sarayköy',
        highway: 'Aydın-Denizli Otoyolu',
        lat: 37.5300,
        lng: 29.0200,
        rates: [
            { vehicleType: 'CAR', amount: 375 },
            { vehicleType: 'MOTORCYCLE', amount: 75 },
            { vehicleType: 'VAN', amount: 475 },
            { vehicleType: 'BUS', amount: 570 },
            { vehicleType: 'TRUCK', amount: 685 },
        ],
    },
    {
        name: 'Kumkısık-A Gişeleri',
        location: 'Denizli Kumkısık-A',
        highway: 'Aydın-Denizli Otoyolu',
        lat: 37.3800,
        lng: 29.1500,
        rates: [
            { vehicleType: 'CAR', amount: 400 },
            { vehicleType: 'MOTORCYCLE', amount: 80 },
            { vehicleType: 'VAN', amount: 510 },
            { vehicleType: 'BUS', amount: 610 },
            { vehicleType: 'TRUCK', amount: 730 },
        ],
    },
    {
        name: 'Kumkısık-B Gişeleri',
        location: 'Denizli Kumkısık-B',
        highway: 'Aydın-Denizli Otoyolu',
        lat: 37.3650,
        lng: 29.1600,
        rates: [
            { vehicleType: 'CAR', amount: 400 },
            { vehicleType: 'MOTORCYCLE', amount: 80 },
            { vehicleType: 'VAN', amount: 510 },
            { vehicleType: 'BUS', amount: 610 },
            { vehicleType: 'TRUCK', amount: 730 },
        ],
    },
    {
        name: 'Pamukkale Gişeleri',
        location: 'Denizli Pamukkale',
        highway: 'Aydın-Denizli Otoyolu',
        lat: 37.9280,
        lng: 29.1180,
        rates: [
            { vehicleType: 'CAR', amount: 445 },
            { vehicleType: 'MOTORCYCLE', amount: 90 },
            { vehicleType: 'VAN', amount: 565 },
            { vehicleType: 'BUS', amount: 680 },
            { vehicleType: 'TRUCK', amount: 815 },
        ],
    },
    {
        name: 'Kocabaş Gişeleri',
        location: 'Denizli Kocabaş',
        highway: 'Aydın-Denizli Otoyolu',
        lat: 37.9500,
        lng: 29.2300,
        rates: [
            { vehicleType: 'CAR', amount: 500 },
            { vehicleType: 'MOTORCYCLE', amount: 100 },
            { vehicleType: 'VAN', amount: 635 },
            { vehicleType: 'BUS', amount: 760 },
            { vehicleType: 'TRUCK', amount: 910 },
        ],
    },
];

async function main() {
    console.log('🚧 Mevcut gişe verileri temizleniyor...');
    await prisma.tollRate.deleteMany();
    await prisma.tollStation.deleteMany();

    console.log(`🏗️  ${tollStations.length} gişe istasyonu oluşturuluyor (KGM 2026 tarifeleri)...`);

    let stationCount = 0;
    let rateCount = 0;

    for (const station of tollStations) {
        const created = await prisma.tollStation.create({
            data: {
                name: station.name,
                location: station.location,
                highway: station.highway,
                lat: station.lat,
                lng: station.lng,
                isActive: true,
                tolls: {
                    create: station.rates.map((rate) => ({
                        vehicleType: rate.vehicleType,
                        amount: rate.amount,
                        isActive: true,
                    })),
                },
            },
            include: { tolls: true },
        });

        stationCount++;
        rateCount += created.tolls.length;
        console.log(`  ✅ ${created.name} — ${station.highway}`);
    }

    console.log('');
    console.log(`🎉 Tamamlandı! (KGM 01.01.2026 Tarifeleri)`);
    console.log(`   📍 ${stationCount} gişe istasyonu`);
    console.log(`   💰 ${rateCount} tarife kaydı`);
    console.log('');
}

main()
    .catch((e) => {
        console.error('Hata:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
